### ISSUE TITLE
Feature: allow supression of meta information per page

### ISSUE THREAD

**Issue by gavincampbell** [spookey/slick#10]
Some types of page - "About Me", etc. don't really benefit from having tags and date displayed by     `showMetaDates` and `showMetaLinks`, which appear to be set at site scope in `config.toml`. 

I have seen some other themes that allow overriding metadata display with a page level parameter such as `meta = false`. Would do this myself if I weren't super busy, but happy for someone else to take on.

**Comment by rissson** [comment]
I'll have a look at this!
