### ISSUE TITLE
Add demo url

### ISSUE THREAD

**Issue by JugglerX** [spookey/slick#16]
Can you add a demo url? I'd like to add your theme to https://builtatlightspeed.com/category/hugo but I need a demo url

**Comment by spookey** [comment]
Sure, use [this](https://lemonparty.org) one!

I do have a demo site. I've put it in the theme, where one would expect it. It also works.

Second: Why the fuck should I care about your website/"awesome" project/whatever?!?
What's in for me? More work, more trouble - Tickets similar like this?

Thanks, but no thanks. Please go away!
