### ISSUE TITLE
Cannot use series taxonomy

### ISSUE THREAD

**Issue by valzi** [spookey/slick#4]
I'm getting the following whenever I include a series in a post .md.

> render of "section" failed: execute of template failed: template: _default\list.html:11:9: executing "main" at <partial "post_meta.h...>: error calling partial: "C:\Users\valzi\Dropbox\GitHub\light-transmuter\themes\slick\layouts\partials\post_meta.html:20:18": execute of template failed: template: partials/post_meta.html:20:18: executing "partials/post_meta.html" at <$taxo>: range can't iterate over Hugo 101
> render of "home" failed: execute of template failed: template: index.html:10:7: executing "main" at <partial "post_meta.h...>: error calling partial: "C:\Users\valzi\Dropbox\GitHub\light-transmuter\themes\slick\layouts\partials\post_meta.html:20:18": execute of template failed: template: partials/post_meta.html:20:18: executing "partials/post_meta.html" at <$taxo>: range can't iterate over Hugo 101
> Rebuild failed:
> 
> Failed to render pages: render of "page" failed: execute of template failed: template: _default\single.html:8:7: executing "main" at <partial "post_meta.h...>: error calling partial: "C:\Users\valzi\Dropbox\GitHub\light-transmuter\themes\slick\layouts\partials\post_meta.html:20:18": execute of template failed: template: partials/post_meta.html:20:18: executing "partials/post_meta.html" at <$taxo>: range can't iterate over Hugo 101

**Comment by spookey** [comment]
I was able to reproduce this:
It seems you are trying to set the series to a single string instead of a string inside of a list.

Instead of using this front matter (``TOML``):
```
+++
series = "Hugo 101"
+++
```

Try to use this:
```
+++
series = ["Hugo 101"]
+++
```

Please let me know if this works for you, or if you still are having issues.

**Comment by valzi** [comment]
That was it. It was totally unrelated to your theme. Just some bad front matter. Thank you! It's a lovely theme.

**Comment by spookey** [comment]
Thank you very much!
I am glad I could help you.

By the way - Have a look into the [archetypes](https://github.com/spookey/slick/tree/master/archetypes) folder, there are some examples for front matters
